### ISSUE TITLE
Is it possible to override an existing framework used by the app?

### ISSUE THREAD

**Issue by mgcrea** [depoon/iOSDylibInjectionDemo#5]
I'm trying to sideload an App to debug WebSocket connections, the app uses [Starscream](https://github.com/daltoniam/Starscream).

I've tried to manually patch the Starscream source code like [this line](https://github.com/daltoniam/Starscream/blob/master/Sources/Starscream/WebSocket.swift#L541)  to add debug `print` and to sideload it along my working injection and it looks like the original app still uses its original framework and not my patched version as I don't get any logs.

Is there a way to force the original app to use my patch framework? Or do I have to somehow overload the method? Any help/guidance would be greatly appreciated... I'm getting close! Thanks again for the great work.

**Comment by null48** [comment]
Null48 - APK Download Free App Android and Ipa iOS Game

Website For Free Download Game, Software (Android, IOS, Windows Phone) 

Null48.Net Check out Guys.

https://null48.net/

Null48 is a website for App And Game APK free download Phone Android, Ipa IOS, Windows Phone, Virtual Reality Glasses (VR), PPSSPP Games.

-------------------------------------
And Also This WebSite Sponsor By This Youtube Channel (Zed Styles):

https://www.youtube.com/c/zedstyles

**Comment by depoon** [comment]
Sorry for the late reply. 

1. Use method swizzling.
2. Make sure method swizzling is executed before any app code does.

Use static void __attribute__((constructor))

**Comment by depoon** [comment]
@mgcrea Any other issues?

**Comment by depoon** [comment]
@mgcrea any updates?

**Comment by mgcrea** [comment]
@depoon I did find another way to reverse engineer the protocol so in the end I did not make it work. But I guess I was pretty close. Might revisit in the future if I finally need it! Thanks for your help & project!

**Comment by depoon** [comment]
Wow care to share light?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mgcrea** [comment]
Unfortunately nothing fancy, just did browse the decompiled android source of the app code to guess the websocket API signature!
